//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// 原始文件名:
// 生成日期: 2012-12-24 17:35:05
namespace LStu.Models
{
    
    /// <summary>
    /// 架构中不存在 ProfileEntities 的注释。
    /// </summary>
    public partial class ProfileEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“ProfileEntities”部分中的连接字符串初始化新 ProfileEntities 对象。
        /// </summary>
        public ProfileEntities() : 
                base("name=ProfileEntities", "ProfileEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 ProfileEntities 对象。
        /// </summary>
        public ProfileEntities(string connectionString) : 
                base(connectionString, "ProfileEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 ProfileEntities 对象。
        /// </summary>
        public ProfileEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ProfileEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 T_Profile 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<T_Profile> T_Profile
        {
            get
            {
                if ((this._T_Profile == null))
                {
                    this._T_Profile = base.CreateQuery<T_Profile>("[T_Profile]");
                }
                return this._T_Profile;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<T_Profile> _T_Profile;
        /// <summary>
        /// 架构中不存在 T_ProfileTemporary 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<T_ProfileTemporary> T_ProfileTemporary
        {
            get
            {
                if ((this._T_ProfileTemporary == null))
                {
                    this._T_ProfileTemporary = base.CreateQuery<T_ProfileTemporary>("[T_ProfileTemporary]");
                }
                return this._T_ProfileTemporary;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<T_ProfileTemporary> _T_ProfileTemporary;
        /// <summary>
        /// 架构中不存在 T_Profile 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToT_Profile(T_Profile t_Profile)
        {
            base.AddObject("T_Profile", t_Profile);
        }
        /// <summary>
        /// 架构中不存在 T_ProfileTemporary 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToT_ProfileTemporary(T_ProfileTemporary t_ProfileTemporary)
        {
            base.AddObject("T_ProfileTemporary", t_ProfileTemporary);
        }
    }
    /// <summary>
    /// 架构中不存在 Data.T_Profile 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Serial_Code
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Data", Name="T_Profile")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class T_Profile : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 T_Profile 对象。
        /// </summary>
        /// <param name="serial_Code">Serial_Code 的初始值。</param>
        /// <param name="enterprise_Name">Enterprise_Name 的初始值。</param>
        /// <param name="project_Name">Project_Name 的初始值。</param>
        /// <param name="project_Content">Project_Content 的初始值。</param>
        /// <param name="project_Code">Project_Code 的初始值。</param>
        /// <param name="project_Picture_Code">Project_Picture_Code 的初始值。</param>
        /// <param name="project_Date">Project_Date 的初始值。</param>
        /// <param name="project_Version">Project_Version 的初始值。</param>
        /// <param name="project_Design_Stage">Project_Design_Stage 的初始值。</param>
        /// <param name="professional">Professional 的初始值。</param>
        /// <param name="create_Date">Create_Date 的初始值。</param>
        /// <param name="creator">Creator 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static T_Profile CreateT_Profile(string serial_Code, string enterprise_Name, string project_Name, string project_Content, string project_Code, string project_Picture_Code, global::System.DateTime project_Date, string project_Version, string project_Design_Stage, string professional, global::System.DateTime create_Date, string creator)
        {
            T_Profile t_Profile = new T_Profile();
            t_Profile.Serial_Code = serial_Code;
            t_Profile.Enterprise_Name = enterprise_Name;
            t_Profile.Project_Name = project_Name;
            t_Profile.Project_Content = project_Content;
            t_Profile.Project_Code = project_Code;
            t_Profile.Project_Picture_Code = project_Picture_Code;
            t_Profile.Project_Date = project_Date;
            t_Profile.Project_Version = project_Version;
            t_Profile.Project_Design_Stage = project_Design_Stage;
            t_Profile.Professional = professional;
            t_Profile.Create_Date = create_Date;
            t_Profile.Creator = creator;
            return t_Profile;
        }
        /// <summary>
        /// 架构中不存在属性 Serial_Code 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Serial_Code
        {
            get
            {
                return this._Serial_Code;
            }
            set
            {
                this.OnSerial_CodeChanging(value);
                this.ReportPropertyChanging("Serial_Code");
                this._Serial_Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Serial_Code");
                this.OnSerial_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Serial_Code;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSerial_CodeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSerial_CodeChanged();
        /// <summary>
        /// 架构中不存在属性 Enterprise_Name 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Enterprise_Name
        {
            get
            {
                return this._Enterprise_Name;
            }
            set
            {
                this.OnEnterprise_NameChanging(value);
                this.ReportPropertyChanging("Enterprise_Name");
                this._Enterprise_Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Enterprise_Name");
                this.OnEnterprise_NameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Enterprise_Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEnterprise_NameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEnterprise_NameChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Name 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Name
        {
            get
            {
                return this._Project_Name;
            }
            set
            {
                this.OnProject_NameChanging(value);
                this.ReportPropertyChanging("Project_Name");
                this._Project_Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Name");
                this.OnProject_NameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_NameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_NameChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Content 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Content
        {
            get
            {
                return this._Project_Content;
            }
            set
            {
                this.OnProject_ContentChanging(value);
                this.ReportPropertyChanging("Project_Content");
                this._Project_Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Content");
                this.OnProject_ContentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Content;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_ContentChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_ContentChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Code 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Code
        {
            get
            {
                return this._Project_Code;
            }
            set
            {
                this.OnProject_CodeChanging(value);
                this.ReportPropertyChanging("Project_Code");
                this._Project_Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Code");
                this.OnProject_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Code;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_CodeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_CodeChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Picture_Code 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Picture_Code
        {
            get
            {
                return this._Project_Picture_Code;
            }
            set
            {
                this.OnProject_Picture_CodeChanging(value);
                this.ReportPropertyChanging("Project_Picture_Code");
                this._Project_Picture_Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Picture_Code");
                this.OnProject_Picture_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Picture_Code;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_Picture_CodeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_Picture_CodeChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Date 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime Project_Date
        {
            get
            {
                return this._Project_Date;
            }
            set
            {
                this.OnProject_DateChanging(value);
                this.ReportPropertyChanging("Project_Date");
                this._Project_Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Project_Date");
                this.OnProject_DateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _Project_Date;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_DateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_DateChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Version 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Version
        {
            get
            {
                return this._Project_Version;
            }
            set
            {
                this.OnProject_VersionChanging(value);
                this.ReportPropertyChanging("Project_Version");
                this._Project_Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Version");
                this.OnProject_VersionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Version;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_VersionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_VersionChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Design_Stage 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Design_Stage
        {
            get
            {
                return this._Project_Design_Stage;
            }
            set
            {
                this.OnProject_Design_StageChanging(value);
                this.ReportPropertyChanging("Project_Design_Stage");
                this._Project_Design_Stage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Design_Stage");
                this.OnProject_Design_StageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Design_Stage;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_Design_StageChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_Design_StageChanged();
        /// <summary>
        /// 架构中不存在属性 Professional 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Professional
        {
            get
            {
                return this._Professional;
            }
            set
            {
                this.OnProfessionalChanging(value);
                this.ReportPropertyChanging("Professional");
                this._Professional = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Professional");
                this.OnProfessionalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Professional;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProfessionalChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProfessionalChanged();
        /// <summary>
        /// 架构中不存在属性 Create_Date 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime Create_Date
        {
            get
            {
                return this._Create_Date;
            }
            set
            {
                this.OnCreate_DateChanging(value);
                this.ReportPropertyChanging("Create_Date");
                this._Create_Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Create_Date");
                this.OnCreate_DateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _Create_Date;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCreate_DateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCreate_DateChanged();
        /// <summary>
        /// 架构中不存在属性 Creator 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Creator
        {
            get
            {
                return this._Creator;
            }
            set
            {
                this.OnCreatorChanging(value);
                this.ReportPropertyChanging("Creator");
                this._Creator = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Creator");
                this.OnCreatorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Creator;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCreatorChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCreatorChanged();
    }
    /// <summary>
    /// 架构中不存在 Data.T_ProfileTemporary 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Serial_Code
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Data", Name="T_ProfileTemporary")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class T_ProfileTemporary : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 T_ProfileTemporary 对象。
        /// </summary>
        /// <param name="serial_Code">Serial_Code 的初始值。</param>
        /// <param name="enterprise_Name">Enterprise_Name 的初始值。</param>
        /// <param name="project_Name">Project_Name 的初始值。</param>
        /// <param name="project_Content">Project_Content 的初始值。</param>
        /// <param name="project_Code">Project_Code 的初始值。</param>
        /// <param name="project_Picture_Code">Project_Picture_Code 的初始值。</param>
        /// <param name="project_Date">Project_Date 的初始值。</param>
        /// <param name="project_Version">Project_Version 的初始值。</param>
        /// <param name="project_Design_Stage">Project_Design_Stage 的初始值。</param>
        /// <param name="professional">Professional 的初始值。</param>
        /// <param name="create_Date">Create_Date 的初始值。</param>
        /// <param name="creator">Creator 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static T_ProfileTemporary CreateT_ProfileTemporary(string serial_Code, string enterprise_Name, string project_Name, string project_Content, string project_Code, string project_Picture_Code, global::System.DateTime project_Date, string project_Version, string project_Design_Stage, string professional, global::System.DateTime create_Date, string creator)
        {
            T_ProfileTemporary t_ProfileTemporary = new T_ProfileTemporary();
            t_ProfileTemporary.Serial_Code = serial_Code;
            t_ProfileTemporary.Enterprise_Name = enterprise_Name;
            t_ProfileTemporary.Project_Name = project_Name;
            t_ProfileTemporary.Project_Content = project_Content;
            t_ProfileTemporary.Project_Code = project_Code;
            t_ProfileTemporary.Project_Picture_Code = project_Picture_Code;
            t_ProfileTemporary.Project_Date = project_Date;
            t_ProfileTemporary.Project_Version = project_Version;
            t_ProfileTemporary.Project_Design_Stage = project_Design_Stage;
            t_ProfileTemporary.Professional = professional;
            t_ProfileTemporary.Create_Date = create_Date;
            t_ProfileTemporary.Creator = creator;
            return t_ProfileTemporary;
        }
        /// <summary>
        /// 架构中不存在属性 Serial_Code 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Serial_Code
        {
            get
            {
                return this._Serial_Code;
            }
            set
            {
                this.OnSerial_CodeChanging(value);
                this.ReportPropertyChanging("Serial_Code");
                this._Serial_Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Serial_Code");
                this.OnSerial_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Serial_Code;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSerial_CodeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSerial_CodeChanged();
        /// <summary>
        /// 架构中不存在属性 Enterprise_Name 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Enterprise_Name
        {
            get
            {
                return this._Enterprise_Name;
            }
            set
            {
                this.OnEnterprise_NameChanging(value);
                this.ReportPropertyChanging("Enterprise_Name");
                this._Enterprise_Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Enterprise_Name");
                this.OnEnterprise_NameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Enterprise_Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEnterprise_NameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEnterprise_NameChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Name 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Name
        {
            get
            {
                return this._Project_Name;
            }
            set
            {
                this.OnProject_NameChanging(value);
                this.ReportPropertyChanging("Project_Name");
                this._Project_Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Name");
                this.OnProject_NameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_NameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_NameChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Content 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Content
        {
            get
            {
                return this._Project_Content;
            }
            set
            {
                this.OnProject_ContentChanging(value);
                this.ReportPropertyChanging("Project_Content");
                this._Project_Content = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Content");
                this.OnProject_ContentChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Content;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_ContentChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_ContentChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Code 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Code
        {
            get
            {
                return this._Project_Code;
            }
            set
            {
                this.OnProject_CodeChanging(value);
                this.ReportPropertyChanging("Project_Code");
                this._Project_Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Code");
                this.OnProject_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Code;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_CodeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_CodeChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Picture_Code 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Picture_Code
        {
            get
            {
                return this._Project_Picture_Code;
            }
            set
            {
                this.OnProject_Picture_CodeChanging(value);
                this.ReportPropertyChanging("Project_Picture_Code");
                this._Project_Picture_Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Picture_Code");
                this.OnProject_Picture_CodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Picture_Code;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_Picture_CodeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_Picture_CodeChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Date 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime Project_Date
        {
            get
            {
                return this._Project_Date;
            }
            set
            {
                this.OnProject_DateChanging(value);
                this.ReportPropertyChanging("Project_Date");
                this._Project_Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Project_Date");
                this.OnProject_DateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _Project_Date;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_DateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_DateChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Version 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Version
        {
            get
            {
                return this._Project_Version;
            }
            set
            {
                this.OnProject_VersionChanging(value);
                this.ReportPropertyChanging("Project_Version");
                this._Project_Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Version");
                this.OnProject_VersionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Version;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_VersionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_VersionChanged();
        /// <summary>
        /// 架构中不存在属性 Project_Design_Stage 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Project_Design_Stage
        {
            get
            {
                return this._Project_Design_Stage;
            }
            set
            {
                this.OnProject_Design_StageChanging(value);
                this.ReportPropertyChanging("Project_Design_Stage");
                this._Project_Design_Stage = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Project_Design_Stage");
                this.OnProject_Design_StageChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Project_Design_Stage;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_Design_StageChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProject_Design_StageChanged();
        /// <summary>
        /// 架构中不存在属性 Professional 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Professional
        {
            get
            {
                return this._Professional;
            }
            set
            {
                this.OnProfessionalChanging(value);
                this.ReportPropertyChanging("Professional");
                this._Professional = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Professional");
                this.OnProfessionalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Professional;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProfessionalChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnProfessionalChanged();
        /// <summary>
        /// 架构中不存在属性 Create_Date 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime Create_Date
        {
            get
            {
                return this._Create_Date;
            }
            set
            {
                this.OnCreate_DateChanging(value);
                this.ReportPropertyChanging("Create_Date");
                this._Create_Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Create_Date");
                this.OnCreate_DateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _Create_Date;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCreate_DateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCreate_DateChanged();
        /// <summary>
        /// 架构中不存在属性 Creator 的任何注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Creator
        {
            get
            {
                return this._Creator;
            }
            set
            {
                this.OnCreatorChanging(value);
                this.ReportPropertyChanging("Creator");
                this._Creator = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Creator");
                this.OnCreatorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Creator;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCreatorChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCreatorChanged();
    }
}
